#!/bin/bash

set -euxo pipefail

source ../../../lib/bash-login.sh

source ../../../lib/names.sh

gcloud container clusters get-credentials ${TF_VAR_cluster_name} --zone ${TF_VAR_cluster_zone} --project $(gcloud projects list  --format="csv[no-heading](PROJECT_ID)")

kubectl create -f tiller-rbac-config.yaml
helm init --service-account tiller

source ../../../lib/bash-logout.sh