#!/bin/bash

set -euxo pipefail

gcloud auth application-default login

source ../../names.sh

gcloud container clusters get-credentials ${TF_VAR_cluster_name} --zone ${TF_VAR_cluster_zone} --project $(gcloud projects list  --format="csv[no-heading](PROJECT_ID)")

kubectl create -f tiller-rbac-config.yaml
helm init --service-account tiller

gcloud auth application-default revoke -q