#!/bin/bash

set -euxo pipefail

source lib/create_service_account_cred.sh

# Terraform provisions resources
cd resource-definitions && terraform init && terraform apply

source lib/remove_service_account_cred.sh

