#!/bin/bash

set -euxo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source ${script_dir}/lib/names.sh

gcloud auth login

cd ${script_dir}/cloud-project && ./create
cd ${script_dir}/cloud-project/storage && ./create

gcloud auth revoke -q
