#!/bin/bash

set -euxo pipefail

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

gcloud auth login

cd ${script_dir}/cloud-project && ./delete 
cd ${script_dir}/cloud-project/terraform && rm .terraform/terraform.tfstate 2> /dev/null  

gcloud auth revoke -q
