#!/bin/bash

set -euxo pipefail

keyfile=~/.config/gcloud/terraform-admin.json

gcloud auth login

export TF_VAR_project_id="$(gcloud config get-value project)"

gcloud iam service-accounts keys create "${keyfile}" --iam-account terraform@"${TF_VAR_project_id}".iam.gserviceaccount.com

terraform destroy

gcloud projects delete "${TF_VAR_project_id}"

gcloud auth revoke

rm "${keyfile}"