#!/bin/bash

set -euxo pipefail

root_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export BASH_AUTH_INVOKE=true
export BASH_AUTH_REVOKE=true

cd ${root_dir}/cloud-project && ./delete 
cd ${root_dir}/cloud-project/ip && rm .terraform/terraform.tfstate 2> /dev/null 
cd ${root_dir}/cloud-project/kubernetes-cluster && rm .terraform/terraform.tfstate 2> /dev/null  
cd ${root_dir}/cloud-project/service-account && rm .terraform/terraform.tfstate 2> /dev/null 