#!/bin/bash

set -euxo pipefail

gcloud auth application-default login

source ../names.sh

gsutil mb -p $(gcloud projects list  --format="csv[no-heading](PROJECT_ID)") gs://${BUCKET}

gcloud auth application-default revoke -q

