#!/bin/bash

set -euxo pipefail

gcloud auth login

project_id=$(gcloud projects list  --format="csv[no-heading](PROJECT_ID)")
bucket=${project_id}-terraform-state

gsutil mb -p ${project_id} gs://${bucket}

gcloud auth revoke -q

declare -a files=("../service-account/service_account.tf" "../service-account/account-role/main.tf" "../kubernetes-cluster/cluster.tf" "../ip/ip.tf")

for file in "${files[@]}"
do 
    sed 's/shift-scheduler-[0-9]\{1,5\}-terraform-state/'${bucket}'/' ${file} > ${file}.bk
    mv ${file}.bk ${file}
    git add ${file}
    git commit -m "Changed bucket name as a result of an auto created bucket."
    #git push
done