#!/bin/bash

set -euxo pipefail

gcloud auth login

gsutil rm -r gs://$(gcloud projects list  --format="csv[no-heading](PROJECT_ID)")-terraform-state

gcloud auth revoke -q

declare -a files=("../service-account/service_account.tf" "../service-account/account-role/main.tf" "../kubernetes-cluster/cluster.tf" "../ip/ip.tf")

for file in "${files[@]}"
do 
    sed 's/shift-scheduler-[0-9]\{0,5\}-terraform-state/shift-scheduler-00000-terraform-state/' ${file} | tee ${file}
    git add ${file}
    git commit -m "Reset bucket name as a result of the auto removal of the bucket."
    git push
done