#!/bin/bash

set -euxo pipefail

gcloud auth application-default login

source ../names.sh

gcloud iam service-accounts delete ${SERVICE_ACCOUNT}@$(gcloud projects list  --format="csv[no-heading](PROJECT_ID)").iam.gserviceaccount.com

gcloud auth application-default revoke -q

deployment_repo_dir=../../../shift-scheduler-deployment
cd ${deployment_repo_dir}
rm ${SERVICE_ACCOUNT}-key.json.enc
git add ${SERVICE_ACCOUNT}-key.json.enc
git commit -m "Deleted deploy service account."
git push


