#!/bin/bash

set -euxo pipefail

gcloud auth application-default login

gcloud projects delete $(gcloud projects list  --format="csv[no-heading](PROJECT_ID)")

gcloud auth application-default revoke -q