#!/bin/bash

set -euxo pipefail

gcloud auth login
export TF_VAR_project_id="$(gcloud projects list  --format="csv[no-heading](PROJECT_ID)")"
gcloud auth revoke -q

gcloud auth application-default login
source ../names.sh
terraform init && terraform apply
gcloud auth application-default revoke -q