#!/bin/bash

set -euxo pipefail

gcloud auth application-default login

source ../names.sh
export TF_VAR_project_id="$(gcloud projects list  --format="csv[no-heading](PROJECT_ID)")"
terraform init && terraform apply

gcloud auth application-default revoke -q