#!/bin/bash

set -euxo pipefail

project_id=shift-scheduler-"${RANDOM}"

gcloud auth login

# Get the account ID like "71B5CC-6X99F1-D483A5"
billing_account="$(gcloud beta billing accounts list --format="csv[no-heading](ACCOUNT_ID)")"

# Create a project to house all the resources 
gcloud projects create "${project_id}" --set-as-default
gcloud beta billing projects link "${project_id}" --billing-account "${billing_account}"

#Create the Terraform service account
gcloud iam service-accounts create terraform --display-name "Terraform admin account" 
gcloud projects add-iam-policy-binding "${project_id}" --member serviceAccount:terraform@"${project_id}".iam.gserviceaccount.com --role roles/owner

gcloud services enable cloudresourcemanager.googleapis.com
gcloud services enable cloudbilling.googleapis.com
gcloud services enable iam.googleapis.com
gcloud services enable compute.googleapis.com
gcloud services enable container.googleapis.com

../auth/remove_service_account_cred