#!/bin/bash

set -euxo pipefail

../auth/create_service_account_cred

project_id="$(gcloud projects list  --format="csv[no-heading](PROJECT_ID)")"
gcloud projects delete "${project_id}"

../auth/remove_service_account_cred