#!/bin/bash

set -euxo pipefail

../auth/create_service_account_cred

export GOOGLE_APPLICATION_CREDENTIALS=~/.config/gcloud/terraform-admin.json
export TF_VAR_project_id="$(gcloud projects list  --format="csv[no-heading](PROJECT_ID)")"

# Terraform provisions resources
terraform init && terraform apply

../auth/remove_service_account_cred

